# Generated by Django 6.1 on 2026-08-21 19:54

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoría de producto',
                'verbose_name_plural': 'Categorías de productos',
                'db_table': 'producto_categoria',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('unidad_medida', models.CharField(choices=[('unidad', 'Unidad'), ('fajo', 'Fajo'), ('metro', 'Metro')], max_length=20)),
                ('pais_origen', models.CharField(blank=True, max_length=100)),
                ('estado', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='productos.productocategoria')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'producto',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='ProductoVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=100)),
                ('apto_alimento', models.BooleanField(default=False)),
                ('micraje', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('color_bolsa', models.CharField(blank=True, max_length=100)),
                ('impresion', models.BooleanField(default=False)),
                ('color_impresion', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list)),
                ('tipo_impresion', models.CharField(blank=True, max_length=100)),
                ('numero_version', models.PositiveIntegerField()),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('inactiva', 'Inactiva')], default='activa', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versiones', to='productos.producto')),
            ],
            options={
                'verbose_name': 'Versión de producto',
                'verbose_name_plural': 'Versiones de producto',
                'db_table': 'producto_version',
                'ordering': ['producto', '-numero_version'],
            },
        ),
        migrations.CreateModel(
            name='EspecificacionBolsa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ancho_doblado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ancho_desdoblado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('largo_doblado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('largo_desdoblado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fuelle', models.BooleanField(default=False)),
                ('fuelle_izquierdo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fuelle_derecho', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fuelle_inferior', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fuelle_superior', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tipo_troquel', models.CharField(blank=True, max_length=100)),
                ('tipo_sello', models.CharField(blank=True, max_length=100)),
                ('pestana', models.CharField(blank=True, max_length=100)),
                ('otras_caracteristicas', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('producto_version', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='especificacion_bolsa', to='productos.productoversion')),
            ],
            options={
                'verbose_name': 'Especificación de bolsa',
                'verbose_name_plural': 'Especificaciones de bolsa',
                'db_table': 'especificacion_bolsa',
            },
        ),
        migrations.CreateModel(
            name='EspecificacionBobina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ancho', models.DecimalField(decimal_places=2, max_digits=10)),
                ('diametro', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('diametro_nucleo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tipo_nucleo', models.CharField(blank=True, max_length=100)),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('otras_caracteristicas', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('producto_version', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='especificacion_bobina', to='productos.productoversion')),
            ],
            options={
                'verbose_name': 'Especificación de bobina',
                'verbose_name_plural': 'Especificaciones de bobina',
                'db_table': 'especificacion_bobina',
            },
        ),
        migrations.AddConstraint(
            model_name='productoversion',
            constraint=models.UniqueConstraint(fields=('producto', 'numero_version'), name='unique_producto_version'),
        ),
    ]
