# Generated by Django 6.1 on 2026-08-21 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ControlCalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiempo_control', models.DecimalField(decimal_places=2, max_digits=10)),
                ('momento_control', models.CharField(max_length=50)),
                ('resultado', models.CharField(max_length=100)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_control', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Control de calidad',
                'verbose_name_plural': 'Controles de calidad',
                'db_table': 'control_calidad',
                'ordering': ['-fecha_control'],
            },
        ),
        migrations.CreateModel(
            name='ControlConfeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ancho_medido', models.DecimalField(decimal_places=2, max_digits=10)),
                ('largo_medido', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fuelle_medido', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tipo_sello', models.CharField(max_length=100)),
                ('calidad_sello', models.CharField(max_length=100)),
                ('tipo_troquel', models.CharField(max_length=100)),
                ('calidad_troquel', models.CharField(max_length=100)),
                ('pestana', models.CharField(max_length=100)),
                ('apariencia', models.CharField(max_length=100)),
                ('observaciones', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Control de confección',
                'verbose_name_plural': 'Controles de confección',
                'db_table': 'control_confeccion',
            },
        ),
        migrations.CreateModel(
            name='ControlExtrusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('micraje_medido', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ancho_medido', models.DecimalField(decimal_places=2, max_digits=10)),
                ('peso_muestra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('apariencia', models.CharField(max_length=100)),
                ('uniformidad', models.CharField(max_length=100)),
                ('resistencia', models.CharField(max_length=100)),
                ('observaciones', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Control de extrusión',
                'verbose_name_plural': 'Controles de extrusión',
                'db_table': 'control_extrusion',
            },
        ),
        migrations.CreateModel(
            name='ControlFlexografia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=100)),
                ('registro_impresion', models.CharField(max_length=100)),
                ('calidad_impresion', models.CharField(max_length=100)),
                ('adhesion_tinta', models.CharField(max_length=100)),
                ('definicion', models.CharField(max_length=100)),
                ('diseno', models.CharField(max_length=100)),
                ('observaciones', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Control de flexografía',
                'verbose_name_plural': 'Controles de flexografía',
                'db_table': 'control_flexo',
            },
        ),
        migrations.CreateModel(
            name='ControlRefilado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ancho_medido', models.DecimalField(decimal_places=2, max_digits=10)),
                ('diametro_medido', models.DecimalField(decimal_places=2, max_digits=10)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=10)),
                ('calidad_bobinado', models.CharField(max_length=100)),
                ('alineacion', models.CharField(max_length=100)),
                ('tension', models.CharField(max_length=100)),
                ('observaciones', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Control de refilado',
                'verbose_name_plural': 'Controles de refilado',
                'db_table': 'control_refilado',
            },
        ),
    ]
