# Generated by Django 6.1 on 2026-08-21 19:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calidad', '0001_initial'),
        ('produccion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='controlcalidad',
            name='produccion_operacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='controles_calidad', to='produccion.produccionoperacion'),
        ),
        migrations.AddField(
            model_name='controlcalidad',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='controles_calidad', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='controlconfeccion',
            name='control_calidad',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='control_confeccion', to='calidad.controlcalidad'),
        ),
        migrations.AddField(
            model_name='controlextrusion',
            name='control_calidad',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='control_extrusion', to='calidad.controlcalidad'),
        ),
        migrations.AddField(
            model_name='controlflexografia',
            name='control_calidad',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='control_flexo', to='calidad.controlcalidad'),
        ),
        migrations.AddField(
            model_name='controlrefilado',
            name='control_calidad',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='control_refilado', to='calidad.controlcalidad'),
        ),
    ]
