# Generated by Django 6.1 on 2026-08-25 17:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calidad', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlcalidad',
            name='momento_control',
            field=models.CharField(choices=[('inicio', 'Inicio'), ('proceso', 'Proceso'), ('final', 'Final')], max_length=20),
        ),
        migrations.AlterField(
            model_name='controlcalidad',
            name='resultado',
            field=models.CharField(choices=[('aprobado', 'Arpbado'), ('rechazado', 'Rechazado'), ('observado', 'Observado')], max_length=20),
        ),
        migrations.AlterField(
            model_name='controlconfeccion',
            name='apariencia',
            field=models.PositiveBigIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MinValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='controlconfeccion',
            name='calidad_sello',
            field=models.PositiveBigIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MinValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='controlconfeccion',
            name='calidad_troquel',
            field=models.PositiveBigIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MinValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='controlextrusion',
            name='apariencia',
            field=models.PositiveBigIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='controlextrusion',
            name='resistencia',
            field=models.PositiveBigIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='controlextrusion',
            name='uniformidad',
            field=models.PositiveBigIntegerField(verbose_name=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='controlflexografia',
            name='calidad_impresion',
            field=models.CharField(choices=[('rechazado', 'Rechazado'), ('aceptable', 'Aceptable'), ('bueno', 'Bueno'), ('muy_bueno', 'Muy bueno')], max_length=20),
        ),
        migrations.AlterField(
            model_name='controlrefilado',
            name='alineacion',
            field=models.PositiveBigIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MinValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='controlrefilado',
            name='calidad_bobinado',
            field=models.PositiveBigIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MinValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='controlrefilado',
            name='tension',
            field=models.PositiveBigIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MinValueValidator(5)]),
        ),
    ]
