# Generated by Django 6.1 on 2026-08-25 17:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calidad', '0003_alter_controlcalidad_momento_control_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlcalidad',
            name='resultado',
            field=models.CharField(choices=[('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('observado', 'Observado')], max_length=20),
        ),
        migrations.AlterField(
            model_name='controlextrusion',
            name='uniformidad',
            field=models.PositiveBigIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='controlflexografia',
            name='adhesion_tinta',
            field=models.CharField(choices=[('rechazado', 'Rechazado'), ('aceptable', 'Aceptable'), ('bueno', 'Bueno'), ('muy_bueno', 'Muy bueno')], max_length=20),
        ),
    ]
