# Generated by Django 6.1 on 2026-08-25 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calidad', '0004_alter_controlcalidad_resultado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlconfeccion',
            name='pestana',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='controlconfeccion',
            name='tipo_sello',
            field=models.CharField(choices=[('lateral', 'Lateral'), ('fondo', 'Fondo'), ('fondo_con_pestana', 'Fondo con pestaña')], max_length=20),
        ),
        migrations.AlterField(
            model_name='controlconfeccion',
            name='tipo_troquel',
            field=models.CharField(choices=[('boutique', 'Boutique'), ('boutique_reforzado', 'Boutique reforzado'), ('camiseta', 'Camiseta'), ('bolsa', 'Bolsa'), ('ziper', 'Ziper')], max_length=20),
        ),
    ]
