# Generated by Django 6.1 on 2026-08-25 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calidad', '0005_alter_controlconfeccion_pestana_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlflexografia',
            name='color',
            field=models.CharField(blank=True, default=list, max_length=50),
        ),
    ]
