# Generated by Django 6.1 on 2026-08-25 18:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calidad', '0006_alter_controlflexografia_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlflexografia',
            name='color',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list),
        ),
    ]
