# Generated by Django 6.1 on 2026-08-31 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calidad', '0008_alter_controlconfeccion_apariencia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlcalidad',
            name='tiempo_control',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
