# Generated by Django 6.1 on 2026-08-31 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calidad', '0009_alter_controlcalidad_tiempo_control'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlcalidad',
            name='resultado',
            field=models.CharField(choices=[('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('observado', 'Observado'), ('pendiente', 'Pendiente')], max_length=20),
        ),
    ]
