# Generated by Django 6.1 on 2026-08-21 19:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comercial', '0006_cotizaciondetalle_cotizacionversion_and_more'),
        ('recursos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluacionComercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado', models.CharField(max_length=100)),
                ('fecha', models.DateTimeField()),
                ('observaciones', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('especificacion_producto_solicitado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluaciones_comerciales', to='comercial.especificacionproductosolicitado')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluaciones_comerciales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evaluación comercial',
                'verbose_name_plural': 'Evaluaciones comerciales',
                'db_table': 'evaluacion_comercial',
            },
        ),
        migrations.CreateModel(
            name='EvaluacionViabilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('evaluacion_comercial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluaciones_viabilidad', to='viabilidad.evaluacioncomercial')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluaciones_viabilidad', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evaluación de viabilidad',
                'verbose_name_plural': 'Evaluaciones de viabilidad',
                'db_table': 'evaluacion_viabilidad',
            },
        ),
        migrations.CreateModel(
            name='EvaluacionProceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(max_length=30)),
                ('observaciones', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluaciones_proceso', to=settings.AUTH_USER_MODEL)),
                ('evaluacion_viabilidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluaciones_proceso', to='viabilidad.evaluacionviabilidad')),
            ],
            options={
                'verbose_name': 'Evaluación de proceso',
                'verbose_name_plural': 'Evaluaciones de proceso',
                'db_table': 'evaluacion_proceso',
            },
        ),
        migrations.CreateModel(
            name='ResultadoViabilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado', models.CharField(max_length=100)),
                ('puntaje_viabilidad', models.DecimalField(decimal_places=2, max_digits=5)),
                ('prioridad', models.CharField(max_length=30)),
                ('es_recomendada', models.BooleanField(default=False)),
                ('requiere_adaptacion', models.BooleanField(default=False)),
                ('adaptacion_propuesta', models.TextField(blank=True)),
                ('observacion', models.TextField(blank=True)),
                ('fecha_evaluacion', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('anilla', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resultados_viabilidad', to='recursos.anilla')),
                ('cliche', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resultados_viabilidad', to='recursos.cliche')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resultados_viabilidad', to='recursos.equipo')),
                ('evaluacion_proceso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resultados_viabilidad', to='viabilidad.evaluacionproceso')),
                ('rodillo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resultados_viabilidad', to='recursos.rodillo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resultados_viabilidad', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Resultado de viabilidad',
                'verbose_name_plural': 'Resultados de viabilidad',
                'db_table': 'resultado_viabilidad',
            },
        ),
    ]
