# Generated by Django 6.1 on 2026-08-24 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viabilidad', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluacionproceso',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En proceso'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=30),
        ),
        migrations.AlterField(
            model_name='resultadoviabilidad',
            name='prioridad',
            field=models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta')], default='media', max_length=30),
        ),
    ]
