# Generated by Django 6.1 on 2026-08-27 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos', '0003_capacidadconfeccion_acabado_especial_and_more'),
        ('viabilidad', '0002_alter_evaluacionproceso_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultadoviabilidad',
            name='criterios_evaluados',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='RutaViabilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField()),
                ('proceso', models.CharField(max_length=50)),
                ('observaciones', models.TextField(blank=True)),
                ('evaluacion_viabilidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rutas', to='viabilidad.evaluacionviabilidad')),
                ('maquinaria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rutas_viabilidad', to='recursos.maquinaria')),
            ],
            options={
                'db_table': 'ruta_viabilidad',
                'ordering': ['orden'],
                'constraints': [models.UniqueConstraint(fields=('evaluacion_viabilidad', 'orden'), name='unique_orden_ruta_viabilidad')],
            },
        ),
    ]
