# Generated by Django 6.1 on 2026-08-31 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viabilidad', '0003_resultadoviabilidad_criterios_evaluados_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacionproceso',
            name='proceso',
            field=models.CharField(blank=True, help_text='Tipo de proceso: extrusion, flexografia, confeccion', max_length=50, null=True),
        ),
    ]
