# Generated by Django 6.1 on 2026-08-31 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos', '0005_rename_ancho_max_capacidadconfeccion_bobina_ancho_max_and_more'),
        ('viabilidad', '0004_evaluacionproceso_proceso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rutaviabilidad',
            name='maquinaria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rutas_viabilidad', to='recursos.maquinaria'),
        ),
    ]
