# Generated by Django 6.1 on 2026-08-31 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viabilidad', '0005_alter_rutaviabilidad_maquinaria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluacionviabilidad',
            name='evaluacion_comercial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evaluaciones_viabilidad', to='viabilidad.evaluacioncomercial'),
        ),
    ]
