# Generated by Django 6.1 on 2026-08-31 14:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos', '0005_rename_ancho_max_capacidadconfeccion_bobina_ancho_max_and_more'),
        ('viabilidad', '0006_alter_evaluacionviabilidad_evaluacion_comercial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacionproceso',
            name='maquina_seleccionada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='selecciones_proceso', to='recursos.equipo'),
        ),
        migrations.AddField(
            model_name='evaluacionviabilidad',
            name='aprobado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='aprobaciones_viabilidad', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='evaluacionviabilidad',
            name='estado_aprobacion',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=30),
        ),
        migrations.AddField(
            model_name='evaluacionviabilidad',
            name='fecha_aprobacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
