# Generated by Django 6.1 on 2026-08-21 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comercial', '0006_cotizaciondetalle_cotizacionversion_and_more'),
        ('inventario', '0001_initial'),
        ('productos', '0001_initial'),
        ('recursos', '0001_initial'),
        ('viabilidad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasoRuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('orden_ejecucion', models.PositiveIntegerField()),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paso de ruta',
                'verbose_name_plural': 'Pasos de ruta',
                'db_table': 'paso_ruta',
                'ordering': ['orden_ejecucion'],
            },
        ),
        migrations.CreateModel(
            name='PlanProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_plan', models.DateField()),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('planificado', 'Planificado'), ('en_proceso', 'En proceso'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='borrador', max_length=30)),
                ('observaciones', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plan de producción',
                'verbose_name_plural': 'Planes de producción',
                'db_table': 'plan_produccion',
                'ordering': ['-fecha_plan'],
            },
        ),
        migrations.CreateModel(
            name='RutaProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('inactiva', 'Inactiva')], default='activa', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ruta de producción',
                'verbose_name_plural': 'Rutas de producción',
                'db_table': 'ruta_produccion',
            },
        ),
        migrations.CreateModel(
            name='Dosificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unidad_medida', models.CharField(max_length=30)),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=5)),
                ('activo', models.BooleanField(default=True)),
                ('observaciones', models.TextField(blank=True)),
                ('materia_prima', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dosificaciones', to='inventario.materiaprima')),
                ('producto_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dosificaciones', to='productos.productoversion')),
            ],
            options={
                'verbose_name': 'Dosificación',
                'verbose_name_plural': 'Dosificaciones',
                'db_table': 'dosificacion',
            },
        ),
        migrations.CreateModel(
            name='OrdenProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, unique=True)),
                ('cantidad_planificada', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_inicio_planificada', models.DateTimeField()),
                ('fecha_fin_planificada', models.DateTimeField()),
                ('estado', models.CharField(choices=[('planificada', 'Planificada'), ('en_proceso', 'En proceso'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='planificada', max_length=30)),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('normal', 'Normal'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='normal', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pedido_detalle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_produccion', to='comercial.pedidodetalle')),
            ],
            options={
                'verbose_name': 'Orden de producción',
                'verbose_name_plural': 'Órdenes de producción',
                'db_table': 'orden_produccion',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrdenProduccionDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_programada', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cantidad_atendida', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('estado', models.CharField(choices=[('programada', 'Programada'), ('en_proceso', 'En proceso'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='programada', max_length=30)),
                ('observaciones', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('orden_produccion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles', to='produccion.ordenproduccion')),
                ('pedido_detalle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_produccion', to='comercial.pedidodetalle')),
            ],
            options={
                'verbose_name': 'Detalle de orden de producción',
                'verbose_name_plural': 'Detalles de órdenes de producción',
                'db_table': 'orden_produccion_detalle',
            },
        ),
        migrations.CreateModel(
            name='OrdenRuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='activa', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('orden_produccion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rutas', to='produccion.ordenproduccion')),
                ('ruta_produccion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes', to='produccion.rutaproduccion')),
            ],
            options={
                'verbose_name': 'Ruta de orden de producción',
                'verbose_name_plural': 'Rutas de órdenes de producción',
                'db_table': 'orden_ruta',
            },
        ),
        migrations.CreateModel(
            name='PlanDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_programada', models.DateField()),
                ('cantidad_programada', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estado', models.CharField(choices=[('programado', 'Programado'), ('en_proceso', 'En proceso'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='programado', max_length=30)),
                ('observaciones', models.TextField(blank=True)),
                ('orden_produccion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planes', to='produccion.ordenproduccion')),
                ('plan_produccion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles', to='produccion.planproduccion')),
            ],
            options={
                'verbose_name': 'Detalle de plan de producción',
                'verbose_name_plural': 'Detalles de planes de producción',
                'db_table': 'plan_detalle',
            },
        ),
        migrations.CreateModel(
            name='ProduccionOperacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_operacion', models.PositiveIntegerField()),
                ('fecha_inicio_planificada', models.DateTimeField()),
                ('fecha_inicio_real', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin_planificada', models.DateTimeField()),
                ('fecha_fin_real', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En proceso'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=30)),
                ('cantidad_producida', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('observaciones', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='producciones_operacion', to='recursos.equipo')),
                ('orden_ruta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operaciones', to='produccion.ordenruta')),
                ('resultado_viabilidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='producciones_operacion', to='viabilidad.resultadoviabilidad')),
            ],
            options={
                'verbose_name': 'Operación de producción',
                'verbose_name_plural': 'Operaciones de producción',
                'db_table': 'produccion_operacion',
                'ordering': ['numero_operacion'],
            },
        ),
        migrations.CreateModel(
            name='ConsumoProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_entregada', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cantidad_utilizada', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cantidad_scrap', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('unidad_medida', models.CharField(max_length=30)),
                ('observaciones', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('materia_prima', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumos_produccion', to='inventario.materiaprima')),
                ('produccion_operacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumos', to='produccion.produccionoperacion')),
            ],
            options={
                'verbose_name': 'Consumo de producción',
                'verbose_name_plural': 'Consumos de producción',
                'db_table': 'consumo_produccion',
            },
        ),
        migrations.CreateModel(
            name='ColaOperacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicion', models.PositiveIntegerField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En proceso'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=30)),
                ('fecha_entrada', models.DateTimeField()),
                ('fecha_salida', models.DateTimeField(blank=True, null=True)),
                ('produccion_operacion', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='cola', to='produccion.produccionoperacion')),
            ],
            options={
                'verbose_name': 'Cola de operación',
                'verbose_name_plural': 'Colas de operaciones',
                'db_table': 'cola_operacion',
                'ordering': ['posicion'],
            },
        ),
        migrations.CreateModel(
            name='RutaOperacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiempo_estandar_min', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.TextField(blank=True)),
                ('orden_ejecucion', models.PositiveIntegerField()),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('inactiva', 'Inactiva')], default='activa', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ruta_paso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operaciones', to='produccion.pasoruta')),
            ],
            options={
                'verbose_name': 'Operación de ruta',
                'verbose_name_plural': 'Operaciones de ruta',
                'db_table': 'ruta_operacion',
                'ordering': ['orden_ejecucion'],
            },
        ),
        migrations.AddField(
            model_name='produccionoperacion',
            name='ruta_operacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='producciones', to='produccion.rutaoperacion'),
        ),
        migrations.AddField(
            model_name='pasoruta',
            name='ruta_produccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pasos', to='produccion.rutaproduccion'),
        ),
    ]
