# Generated by Django 6.1 on 2026-08-27 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0001_initial'),
        ('viabilidad', '0003_resultadoviabilidad_criterios_evaluados_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenproduccion',
            name='evaluacion_viabilidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_produccion', to='viabilidad.evaluacionviabilidad'),
        ),
    ]
