# Generated by Django 6.1 on 2026-08-28 17:19

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0002_ordenproduccion_evaluacion_viabilidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultadoProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unidad_medida', models.CharField(max_length=30)),
                ('ancho_obtenido', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('micraje_obtenido', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('material_obtenido', models.CharField(blank=True, max_length=100)),
                ('color_obtenido', models.CharField(blank=True, max_length=100)),
                ('olor', models.CharField(blank=True, max_length=100)),
                ('peso_obtenido', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('impresion', models.BooleanField(default=False)),
                ('colores_obtenidos', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list)),
                ('calidad_color', models.CharField(blank=True, max_length=100)),
                ('tonalidad', models.CharField(blank=True, max_length=100)),
                ('diseno', models.CharField(blank=True, max_length=200)),
                ('posicion_impresion', models.CharField(blank=True, max_length=50)),
                ('distancia_arriba', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('distancia_abajo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('distancia_izquierda', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('distancia_derecha', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('largo_obtenido', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tipo_sello', models.CharField(blank=True, max_length=100)),
                ('tipo_troquel', models.CharField(blank=True, max_length=100)),
                ('estado', models.CharField(choices=[('conforme', 'Conforme'), ('observado', 'Observado'), ('rechazado', 'Rechazado')], default='conforme', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('produccion_operacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resultados_produccion', to='produccion.produccionoperacion')),
            ],
            options={
                'verbose_name': 'Resultado de producción',
                'verbose_name_plural': 'Resultados de producción',
                'db_table': 'resultado_produccion',
                'ordering': ['-created_at'],
            },
        ),
    ]
