# Generated by Django 6.1 on 2026-08-28 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0003_resultadoproduccion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultadoproduccion',
            name='estado',
        ),
        migrations.CreateModel(
            name='LoteProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('cantidad_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('unidad_medida', models.CharField(max_length=30)),
                ('observaciones', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('produccion_operacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes_produccion', to='produccion.produccionoperacion')),
            ],
            options={
                'verbose_name': 'Lote de producción',
                'verbose_name_plural': 'Lotes de producción',
                'db_table': 'lote_produccion',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='resultadoproduccion',
            name='lote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resultados', to='produccion.loteproduccion'),
        ),
    ]
