# Generated by Django 6.1 on 2026-08-28 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0004_remove_resultadoproduccion_estado_loteproduccion_and_more'),
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loteproduccion',
            name='producto_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lotes_produccion', to='productos.productoversion'),
        ),
    ]
