# Generated by Django 6.1 on 2026-08-31 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0010_especificacionproductosolicitado_distancia_impresion_abajo_and_more'),
        ('produccion', '0005_loteproduccion_producto_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenproduccion',
            name='pedido_detalle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_produccion', to='comercial.pedidodetalle'),
        ),
    ]
