# Generated by Django 6.1 on 2026-08-31 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calidad', '0008_alter_controlconfeccion_apariencia_and_more'),
        ('produccion', '0006_alter_ordenproduccion_pedido_detalle'),
    ]

    operations = [
        migrations.CreateModel(
            name='BobinaProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código único de identificación de la bobina', max_length=50, unique=True)),
                ('peso', models.DecimalField(decimal_places=2, help_text='Peso de la bobina en kg', max_digits=12)),
                ('ancho', models.DecimalField(blank=True, decimal_places=2, help_text='Ancho de la bobina en mm', max_digits=10, null=True)),
                ('diametro', models.DecimalField(blank=True, decimal_places=2, help_text='Diámetro de la bobina en mm', max_digits=10, null=True)),
                ('diametro_nucleo', models.DecimalField(blank=True, decimal_places=2, help_text='Diámetro del núcleo en mm', max_digits=10, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=2, help_text='Longitud de la bobina en metros', max_digits=12, null=True)),
                ('estado', models.CharField(choices=[('en_produccion', 'En producción'), ('terminada', 'Terminada'), ('transferida', 'Transferida'), ('rechazada', 'Rechazada'), ('en_almacen', 'En almacén')], default='en_produccion', max_length=30)),
                ('calidad', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('reprocesar', 'Reprocesar'), ('rechazada', 'Rechazada')], default='pendiente', max_length=30)),
                ('fecha_transferencia', models.DateTimeField(blank=True, help_text='Fecha en que se transfirió la bobina', null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_terminacion', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('control_calidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bobinas', to='calidad.controlcalidad')),
                ('operacion_destino', models.ForeignKey(blank=True, help_text='Operación a la que fue transferida esta bobina', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bobinas_recibidas', to='produccion.produccionoperacion')),
                ('produccion_operacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bobinas', to='produccion.produccionoperacion')),
            ],
            options={
                'verbose_name': 'Bobina de producción',
                'verbose_name_plural': 'Bobinas de producción',
                'db_table': 'bobina_produccion',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['codigo'], name='bobina_prod_codigo_289c3d_idx'), models.Index(fields=['estado'], name='bobina_prod_estado_bc5d99_idx'), models.Index(fields=['calidad'], name='bobina_prod_calidad_2e94da_idx'), models.Index(fields=['produccion_operacion'], name='bobina_prod_producc_24e29c_idx')],
            },
        ),
    ]
