# Generated by Django 6.1 on 2026-08-31 17:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calidad', '0008_alter_controlconfeccion_apariencia_and_more'),
        ('produccion', '0007_bobinaproduccion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bobinaproduccion',
            name='lote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bobinas', to='produccion.loteproduccion'),
        ),
        migrations.CreateModel(
            name='MermaProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_merma', models.CharField(choices=[('arranque', 'Arranque'), ('proceso', 'Proceso'), ('calidad', 'Calidad'), ('mantenimiento', 'Mantenimiento'), ('otro', 'Otro')], help_text='Tipo de merma registrada', max_length=30)),
                ('causa', models.CharField(choices=[('configuracion', 'Configuración'), ('material', 'Material defectuoso'), ('equipo', 'Falla de equipo'), ('operador', 'Error operacional'), ('especificacion', 'Cambio especificación'), ('desconocida', 'Causa desconocida'), ('otro', 'Otra causa')], help_text='Causa de la merma', max_length=30)),
                ('cantidad', models.DecimalField(decimal_places=2, help_text='Cantidad de material perdido (en kg o unidad según proceso)', max_digits=12)),
                ('unidad_medida', models.CharField(default='kg', help_text='Unidad de medida de la merma', max_length=30)),
                ('observaciones', models.TextField(blank=True, help_text='Descripción detallada de la merma')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_merma', models.DateTimeField(help_text='Fecha y hora en que ocurrió la merma')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bobina', models.ForeignKey(blank=True, help_text='Bobina asociada si la merma es específica', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mermas', to='produccion.bobinaproduccion')),
                ('control_calidad', models.ForeignKey(blank=True, help_text='Control de calidad que generó la merma', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mermas', to='calidad.controlcalidad')),
                ('produccion_operacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mermas', to='produccion.produccionoperacion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mermas_registradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Merma de producción',
                'verbose_name_plural': 'Mermas de producción',
                'db_table': 'merma_produccion',
                'ordering': ['-fecha_registro'],
                'indexes': [models.Index(fields=['tipo_merma'], name='merma_produ_tipo_me_93287b_idx'), models.Index(fields=['causa'], name='merma_produ_causa_13e34e_idx'), models.Index(fields=['produccion_operacion'], name='merma_produ_producc_415596_idx'), models.Index(fields=['fecha_merma'], name='merma_produ_fecha_m_ad539b_idx')],
            },
        ),
    ]
