# Generated by Django 6.1 on 2026-08-31 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0008_bobinaproduccion_lote_mermaproduccion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferenciaProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('transferida', 'Transferida'), ('rechazada', 'Rechazada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=30)),
                ('calidad_validada', models.BooleanField(default=False, help_text='Indica si la producción fue validada por control de calidad.')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_transferencia', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operacion_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_destino', to='produccion.produccionoperacion')),
                ('operacion_origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_origen', to='produccion.produccionoperacion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_produccion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transferencia de producción',
                'verbose_name_plural': 'Transferencias de producción',
                'db_table': 'transferencia_produccion',
                'ordering': ['-fecha_solicitud'],
            },
        ),
        migrations.CreateModel(
            name='DetalleTransferenciaProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unidad_medida', models.CharField(default='kg', max_length=30)),
                ('observaciones', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bobina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias', to='produccion.bobinaproduccion')),
                ('transferencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles', to='produccion.transferenciaproduccion')),
            ],
            options={
                'verbose_name': 'Detalle de transferencia de producción',
                'verbose_name_plural': 'Detalles de transferencias de producción',
                'db_table': 'detalle_transferencia_produccion',
            },
        ),
    ]
