# Generated by Django 6.1 on 2026-08-31 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calidad', '0008_alter_controlconfeccion_apariencia_and_more'),
        ('produccion', '0009_transferenciaproduccion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detalletransferenciaproduccion',
            options={'verbose_name': 'Detalle de transferencia', 'verbose_name_plural': 'Detalles de transferencia'},
        ),
        migrations.AlterModelOptions(
            name='transferenciaproduccion',
            options={'ordering': ['-created_at'], 'verbose_name': 'Transferencia de producción', 'verbose_name_plural': 'Transferencias de producción'},
        ),
        migrations.RemoveField(
            model_name='detalletransferenciaproduccion',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='detalletransferenciaproduccion',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='transferenciaproduccion',
            name='calidad_validada',
        ),
        migrations.RemoveField(
            model_name='transferenciaproduccion',
            name='fecha_solicitud',
        ),
        migrations.AddField(
            model_name='transferenciaproduccion',
            name='cantidad_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='transferenciaproduccion',
            name='control_calidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_produccion', to='calidad.controlcalidad'),
        ),
        migrations.AddField(
            model_name='transferenciaproduccion',
            name='unidad_medida',
            field=models.CharField(default='kg', max_length=30),
        ),
        migrations.AlterField(
            model_name='detalletransferenciaproduccion',
            name='bobina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_transferencia', to='produccion.bobinaproduccion'),
        ),
        migrations.AlterField(
            model_name='transferenciaproduccion',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('completada', 'Completada')], default='pendiente', max_length=30),
        ),
        migrations.AddConstraint(
            model_name='detalletransferenciaproduccion',
            constraint=models.UniqueConstraint(fields=('transferencia', 'bobina'), name='unique_bobina_transferencia'),
        ),
    ]
