# Generated by Django 6.1 on 2026-08-25 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='almacen',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
