# Generated by Django 6.1 on 2026-08-25 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_alter_almacen_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='estado',
            field=models.CharField(choices=[('disponibleDisponible', 'Disponible'), ('agotado', 'Agotado'), ('bloqueado', 'Bloqueado')], default='disponibleDisponible', max_length=30),
        ),
    ]
