# Generated by Django 6.1 on 2026-08-28 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_alter_inventario_estado'),
        ('produccion', '0005_loteproduccion_producto_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientoinventario',
            name='lote_produccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_inventario', to='produccion.loteproduccion'),
        ),
    ]
