# Generated by Django 6.1 on 2026-08-21 19:54

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comercial', '0006_cotizaciondetalle_cotizacionversion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Área de producción',
                'verbose_name_plural': 'Áreas de producción',
                'db_table': 'area_produccion',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='CapacidadExtrusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(choices=[('PEAD', 'PEAD'), ('PEBD', 'PEBD'), ('PP', 'PP')], max_length=10)),
                ('ancho_min', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ancho_max', models.DecimalField(decimal_places=2, max_digits=10)),
                ('micronaje_min', models.DecimalField(decimal_places=2, max_digits=8)),
                ('micronaje_max', models.DecimalField(decimal_places=2, max_digits=8)),
                ('diametro_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('diametro_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('peso_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('peso_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('kg_h', models.DecimalField(decimal_places=2, max_digits=10)),
                ('capas', models.PositiveIntegerField()),
                ('fuelle_minimo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fuelle_maximo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('observaciones', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Capacidad de extrusión',
                'verbose_name_plural': 'Capacidades de extrusión',
                'db_table': 'capacidad_extrusion',
            },
        ),
        migrations.CreateModel(
            name='Cliche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('grosor_min', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('grosor_max', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('ubicacion', models.CharField(blank=True, max_length=150)),
                ('estado', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cliché',
                'verbose_name_plural': 'Clichés',
                'db_table': 'cliche',
            },
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('tipo_equipo', models.CharField(choices=[('maquinaria', 'Maquinaria'), ('vehiculo', 'Vehículo'), ('infraestructura', 'Infraestructura')], max_length=30)),
                ('marca', models.CharField(blank=True, max_length=100)),
                ('modelo', models.CharField(blank=True, max_length=100)),
                ('estado', models.CharField(choices=[('operativo', 'Operativo'), ('mantenimiento', 'Mantenimiento'), ('fuera_servicio', 'Fuera de servicio')], default='operativo', max_length=30)),
                ('ubicacion', models.CharField(blank=True, max_length=150)),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
                'db_table': 'equipo',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Anilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('diametro', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ancho_min', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ancho_max', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(max_length=30)),
                ('observaciones', models.TextField(blank=True)),
                ('descripcion', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('capacidad_extrusion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='anillas', to='recursos.capacidadextrusion')),
            ],
            options={
                'verbose_name': 'Anilla',
                'verbose_name_plural': 'Anillas',
                'db_table': 'anilla',
            },
        ),
        migrations.CreateModel(
            name='ClicheParte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_piezas', models.PositiveIntegerField()),
                ('colores', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=list, blank=True)),
                ('descripcion', models.TextField(blank=True)),
                ('estado', models.CharField(max_length=30)),
                ('cliche', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partes', to='recursos.cliche')),
            ],
        ),
        migrations.CreateModel(
            name='Diseno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='disenos/')),
                ('version', models.PositiveIntegerField()),
                ('estado', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('especificacion_producto_solicitado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disenos', to='comercial.especificacionproductosolicitado')),
            ],
            options={
                'verbose_name': 'Diseño',
                'verbose_name_plural': 'Diseños',
                'db_table': 'diseno',
                'ordering': ['nombre', '-version'],
            },
        ),
        migrations.AddField(
            model_name='cliche',
            name='diseno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cliches', to='recursos.diseno'),
        ),
        migrations.CreateModel(
            name='Maquinaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True)),
                ('observacion', models.TextField(blank=True)),
                ('area_produccion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maquinarias', to='recursos.areaproduccion')),
                ('equipo', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='maquinaria', to='recursos.equipo')),
            ],
            options={
                'verbose_name': 'Maquinaria',
                'verbose_name_plural': 'Maquinarias',
                'db_table': 'maquinaria',
            },
        ),
        migrations.AddField(
            model_name='cliche',
            name='maquinaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cliches', to='recursos.maquinaria'),
        ),
        migrations.CreateModel(
            name='CapacidadRefilado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ancho_entrada_min', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ancho_entrada_max', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ancho_salida_min', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ancho_salida_max', models.DecimalField(decimal_places=2, max_digits=10)),
                ('velocidad_m_min', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observaciones', models.TextField(blank=True)),
                ('maquinaria', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='capacidad_refilado', to='recursos.maquinaria')),
            ],
            options={
                'verbose_name': 'Capacidad de refilado',
                'verbose_name_plural': 'Capacidades de refilado',
                'db_table': 'capacidad_refilado',
            },
        ),
        migrations.CreateModel(
            name='CapacidadFlexografia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ancho_min', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ancho_max', models.DecimalField(decimal_places=2, max_digits=10)),
                ('colores_min', models.PositiveIntegerField()),
                ('colores_max', models.PositiveIntegerField()),
                ('puede_anverso', models.BooleanField(default=False)),
                ('puede_reverso', models.BooleanField(default=False)),
                ('puede_ambas_caras', models.BooleanField(default=False)),
                ('velocidad_m_min', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observaciones', models.TextField(blank=True)),
                ('maquinaria', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='capacidad_flexografia', to='recursos.maquinaria')),
            ],
            options={
                'verbose_name': 'Capacidad de flexografía',
                'verbose_name_plural': 'Capacidades de flexografía',
                'db_table': 'capacidad_flexografia',
            },
        ),
        migrations.AddField(
            model_name='capacidadextrusion',
            name='maquinaria',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='capacidad_extrusion', to='recursos.maquinaria'),
        ),
        migrations.CreateModel(
            name='CapacidadConfeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materiales', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('PEAD', 'PEAD'), ('PEBD', 'PEBD'), ('PP', 'PP')], max_length=10), blank=True, default=list)),
                ('tipo_sello', models.CharField(max_length=100)),
                ('tipo_troquel', models.CharField(max_length=100)),
                ('ancho_min', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ancho_max', models.DecimalField(decimal_places=2, max_digits=10)),
                ('largo_min', models.DecimalField(decimal_places=2, max_digits=10)),
                ('largo_max', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fuelle_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fuelle_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('velocidad_unidad_min', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observaciones', models.TextField(blank=True)),
                ('maquinaria', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='capacidad_confeccion', to='recursos.maquinaria')),
            ],
            options={
                'verbose_name': 'Capacidad de confección',
                'verbose_name_plural': 'Capacidades de confección',
                'db_table': 'capacidad_confeccion',
            },
        ),
        migrations.CreateModel(
            name='Rodillo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('identificacion', models.CharField(max_length=100)),
                ('medida', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unidad', models.CharField(max_length=20)),
                ('diametro', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ancho', models.DecimalField(decimal_places=2, max_digits=10)),
                ('circunferencia', models.DecimalField(decimal_places=2, max_digits=10)),
                ('desarrollo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observaciones', models.TextField(blank=True)),
                ('estado', models.CharField(max_length=30)),
                ('capacidad_flexografia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rodillos', to='recursos.capacidadflexografia')),
            ],
            options={
                'verbose_name': 'Rodillo',
                'verbose_name_plural': 'Rodillos',
                'db_table': 'rodillo',
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('placa', models.CharField(max_length=20, unique=True)),
                ('marca', models.CharField(blank=True, max_length=100)),
                ('modelo', models.CharField(blank=True, max_length=100)),
                ('capacidad_carga', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo_vehiculo', models.CharField(choices=[('camion', 'Camión'), ('camioneta', 'Camioneta'), ('furgon', 'Furgón'), ('otro', 'Otro')], max_length=30)),
                ('estado', models.CharField(choices=[('operativo', 'Operativo'), ('mantenimiento', 'Mantenimiento'), ('fuera_servicio', 'Fuera de servicio')], default='operativo', max_length=30)),
                ('observacion', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('equipo', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='vehiculo', to='recursos.equipo')),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
                'db_table': 'vehiculo',
            },
        ),
    ]
