# Generated by Django 6.1 on 2026-08-24 18:17

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clicheparte',
            options={'verbose_name': 'Parte de cliché', 'verbose_name_plural': 'Partes de cliché'},
        ),
        migrations.AlterField(
            model_name='clicheparte',
            name='colores',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='clicheparte',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterModelTable(
            name='clicheparte',
            table='cliche_parte',
        ),
    ]
