# Generated by Django 6.1 on 2026-08-27 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos', '0002_alter_clicheparte_options_alter_clicheparte_colores_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='capacidadconfeccion',
            name='acabado_especial',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='capacidadflexografia',
            name='puede_degradado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='capacidadflexografia',
            name='puede_trameado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='capacidadconfeccion',
            name='maquinaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='capacidades_confeccion', to='recursos.maquinaria'),
        ),
        migrations.AlterField(
            model_name='capacidadextrusion',
            name='maquinaria',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='capacidades_extrusion', to='recursos.maquinaria'),
        ),
        migrations.AlterField(
            model_name='capacidadflexografia',
            name='maquinaria',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='capacidades_flexografia', to='recursos.maquinaria'),
        ),
        migrations.AlterField(
            model_name='capacidadrefilado',
            name='maquinaria',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='capacidades_refilado', to='recursos.maquinaria'),
        ),
    ]
