# Generated by Django 6.1 on 2026-08-27 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos', '0003_capacidadconfeccion_acabado_especial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capacidadextrusion',
            name='maquinaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='capacidades_extrusion', to='recursos.maquinaria'),
        ),
    ]
