# Generated by Django 6.1 on 2026-08-28 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos', '0004_alter_capacidadextrusion_maquinaria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='capacidadconfeccion',
            old_name='ancho_max',
            new_name='bobina_ancho_max',
        ),
        migrations.RenameField(
            model_name='capacidadconfeccion',
            old_name='ancho_min',
            new_name='bobina_ancho_min',
        ),
        migrations.AddField(
            model_name='capacidadconfeccion',
            name='producto_ancho_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='capacidadconfeccion',
            name='producto_ancho_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
