# Generated by Django 6.1 on 2026-08-21 19:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comercial', '0006_cotizaciondetalle_cotizacionversion_and_more'),
        ('recursos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Despacho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, unique=True)),
                ('fecha_salida_programada', models.DateTimeField()),
                ('fecha_salida_real', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('programado', 'Programado'), ('en_ruta', 'En ruta'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='programado', max_length=30)),
                ('observaciones', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='despachos', to='comercial.pedido')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='despachos_responsables', to=settings.AUTH_USER_MODEL)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='despachos', to='recursos.vehiculo')),
            ],
            options={
                'verbose_name': 'Despacho',
                'verbose_name_plural': 'Despachos',
                'db_table': 'despacho',
            },
        ),
        migrations.CreateModel(
            name='DespachoDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unidad_medida', models.CharField(max_length=30)),
                ('observaciones', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('despacho', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles', to='despacho.despacho')),
                ('pedido_detalle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='despachos', to='comercial.pedidodetalle')),
            ],
            options={
                'verbose_name': 'Detalle de despacho',
                'verbose_name_plural': 'Detalles de despacho',
                'db_table': 'despacho_detalle',
            },
        ),
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrega_programada', models.DateTimeField()),
                ('fecha_entrega_real', models.DateTimeField(blank=True, null=True)),
                ('hora_entrega', models.TimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('entregada', 'Entregada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=30)),
                ('persona_recibe', models.CharField(max_length=150)),
                ('observaciones', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cuenta_comercial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entregas', to='comercial.cuentacomercial')),
                ('despacho', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entregas', to='despacho.despacho')),
            ],
            options={
                'verbose_name': 'Entrega',
                'verbose_name_plural': 'Entregas',
                'db_table': 'entrega',
            },
        ),
    ]
