# Generated by Django 6.1 on 2026-08-12 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='nombre_completo',
        ),
    ]
