# Generated by Django 6.1 on 2026-09-08 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('auditoria', '0001_crear_modelo_auditoria'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('calidad', '0010_alter_controlcalidad_resultado'),
        ('comercial', '0010_especificacionproductosolicitado_distancia_impresion_abajo_and_more'),
        ('despacho', '0001_initial'),
        ('inventario', '0006_movimientoinventario_lote_produccion'),
        ('notificacion', '0001_initial'),
        ('produccion', '0010_alter_detalletransferenciaproduccion_options_and_more'),
        ('token_blacklist', '0013_alter_blacklistedtoken_options_and_more'),
        ('usuarios', '0003_usuario_delete_customuser'),
        ('viabilidad', '0007_evaluacionproceso_maquina_seleccionada_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuario',
            new_name='CustomUser',
        ),
    ]
