# Generated by Django 6.1 on 2026-08-12 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadComercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('llamada', 'Llamada'), ('reunion', 'Reunión'), ('cotizacion', 'Cotización'), ('seguimiento', 'Seguimiento')], max_length=30)),
                ('descripcion', models.TextField()),
                ('fecha_programada', models.DateTimeField()),
                ('fecha_completada', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En proceso'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], max_length=20)),
                ('resultado', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Actividad comercial',
                'verbose_name_plural': 'Actividades comerciales',
                'db_table': 'actividad_comercial',
            },
        ),
        migrations.CreateModel(
            name='CuentaComercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_persona', models.CharField(choices=[('natural', 'Natural'), ('juridica', 'Jurídica')], max_length=20)),
                ('razon_social', models.CharField(max_length=200)),
                ('identificacion', models.CharField(max_length=50, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('correo', models.EmailField(blank=True, max_length=254)),
                ('direccion', models.CharField(blank=True, max_length=300)),
                ('estado', models.CharField(choices=[('prospecto', 'Prospecto'), ('cliente', 'Cliente'), ('inactivo', 'Inactivo')], default='prospecto', max_length=20)),
                ('fecha_alta', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cuenta comercial',
                'verbose_name_plural': 'Cuentas comerciales',
                'db_table': 'cuenta_comercial',
            },
        ),
    ]
