# Generated by Django 6.1 on 2026-08-12 15:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comercial', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='actividadcomercial',
            name='responsable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actividades_comerciales', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='actividadcomercial',
            name='cuenta_comercial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actividades', to='comercial.cuentacomercial'),
        ),
        migrations.AddIndex(
            model_name='actividadcomercial',
            index=models.Index(fields=['responsable', 'fecha_programada', 'estado'], name='ix_act_com_resp_fecha_estado'),
        ),
    ]
