# Generated by Django 6.1 on 2026-08-12 17:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudComercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('descripcion', models.TextField()),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('normal', 'Normal'), ('alta', 'Alta'), ('urgente', 'Urgente')], max_length=20)),
                ('estado', models.CharField(choices=[('recibida', 'Recibida'), ('en_negociacion', 'En negociación'), ('en_viabilidad', 'En viabilidad'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('convertida', 'Convertida'), ('cancelada', 'Cancelada')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cuenta_comercial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes', to='comercial.cuentacomercial')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_comerciales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud comercial',
                'verbose_name_plural': 'Solicitudes comerciales',
                'db_table': 'solicitud_comercial',
                'indexes': [models.Index(fields=['cuenta_comercial', 'fecha'], name='ix_sol_com_cuenta_fecha')],
            },
        ),
    ]
