# Generated by Django 6.1 on 2026-08-12 17:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0003_solicitudcomercial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comunicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=30)),
                ('medio', models.CharField(max_length=30)),
                ('fecha', models.DateTimeField()),
                ('asunto', models.CharField(blank=True, max_length=200, null=True)),
                ('contenido', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comunicaciones_comerciales', to=settings.AUTH_USER_MODEL)),
                ('solicitud_comercial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comunicaciones', to='comercial.solicitudcomercial')),
            ],
            options={
                'verbose_name': 'Comunicación',
                'verbose_name_plural': 'Comunicaciones',
                'db_table': 'comunicacion',
                'indexes': [models.Index(fields=['solicitud_comercial', 'fecha'], name='ix_com_sol_fecha')],
            },
        ),
    ]
