# Generated by Django 6.1 on 2026-08-21 19:54

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0005_cotizacion'),
        ('productos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CotizacionDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('precio_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Detalle de cotización',
                'verbose_name_plural': 'Detalles de cotización',
                'db_table': 'cotizacion_detalle',
            },
        ),
        migrations.CreateModel(
            name='CotizacionVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('moneda', models.CharField(choices=[('BOB', 'Boliviano'), ('USD', 'Dólares')], default='BOB', max_length=3)),
                ('precio_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('enviada', 'Enviada'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada'), ('anulada', 'Anulada')], default='borrador', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Versión de cotización',
                'verbose_name_plural': 'Versiones de cotización',
                'db_table': 'cotizacion_version',
                'ordering': ['cotizacion', '-version'],
            },
        ),
        migrations.CreateModel(
            name='EspecificacionBobinaSolicitada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ancho', models.DecimalField(decimal_places=2, max_digits=10)),
                ('diametro', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('diametro_nucleo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tipo_nucleo', models.CharField(blank=True, max_length=100)),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('otras_caracteristicas', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Especificación de bobina solicitada',
                'verbose_name_plural': 'Especificaciones de bobinas solicitadas',
                'db_table': 'especificacion_bobina_solicitada',
            },
        ),
        migrations.CreateModel(
            name='EspecificacionBolsaSolicitada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ancho_doblado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ancho_desdoblado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('largo_doblado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('largo_desdoblado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fuelle', models.BooleanField(default=False)),
                ('fuelle_izquierdo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fuelle_derecho', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fuelle_inferior', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fuelle_superior', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tipo_troquel', models.CharField(blank=True, choices=[('camiseta', 'Camiseta'), ('boutique', 'Boutique'), ('aza', 'Aza'), ('boutique_reforzado', 'Boutique reforzado')], max_length=100)),
                ('tipo_sello', models.CharField(choices=[('fondo', 'Fondo'), ('lateral', 'Lateral')], max_length=100)),
                ('pestana', models.CharField(blank=True, max_length=100)),
                ('otras_caracteristicas', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Especificación de bolsa solicitada',
                'verbose_name_plural': 'Especificaciones de bolsa solicitada',
                'db_table': 'especificacion_bolsa_solicitada',
            },
        ),
        migrations.CreateModel(
            name='EspecificacionProductoSolicitado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(choices=[('PEAD', 'PEAD'), ('PEBD', 'PEBD'), ('PP', 'PP')], max_length=20)),
                ('apto_alimento', models.BooleanField(default=False)),
                ('micraje', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('color_bolsa', models.CharField(blank=True, max_length=100)),
                ('impresion', models.BooleanField(default=False)),
                ('color_impresion', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list)),
                ('tipo_impresion', models.CharField(blank=True, choices=[('corrida', 'Corrida'), ('dimensionada', 'Dimensionada')], max_length=20)),
                ('otras_caracteristicas', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Especificación de producto solicitado',
                'verbose_name_plural': 'Especificaciones de productos solicitados',
                'db_table': 'especificacion_producto_solicitado',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, unique=True)),
                ('fecha_pedido', models.DateTimeField()),
                ('estado', models.CharField(choices=[('finalizado', 'Finalizado'), ('en_proceso', 'En proceso')], max_length=30)),
                ('fecha_entrega_comprometida', models.DateTimeField()),
                ('observaciones', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'db_table': 'pedido',
            },
        ),
        migrations.CreateModel(
            name='PedidoDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('precio_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_entrega_comprometida', models.DateTimeField()),
                ('observaciones', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Detalle de pedido',
                'verbose_name_plural': 'Detalles de pedido',
                'db_table': 'pedido_detalle',
            },
        ),
        migrations.RemoveIndex(
            model_name='actividadcomercial',
            name='ix_act_com_resp_fecha_estado',
        ),
        migrations.RemoveIndex(
            model_name='comunicacion',
            name='ix_com_sol_fecha',
        ),
        migrations.RenameField(
            model_name='actividadcomercial',
            old_name='responsable',
            new_name='usuario',
        ),
        migrations.RenameField(
            model_name='comunicacion',
            old_name='responsable',
            new_name='usuario',
        ),
        migrations.RenameField(
            model_name='solicitudcomercial',
            old_name='responsable',
            new_name='usuario',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='version',
        ),
        migrations.AddField(
            model_name='comunicacion',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='cuentacomercial',
            name='apellido_materno',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='cuentacomercial',
            name='apellido_paterno',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='cuentacomercial',
            name='documento_identidad',
            field=models.CharField(blank=True, choices=[('ci', 'CI'), ('nit', 'NIT')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='cuentacomercial',
            name='nombres',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='cuentacomercial',
            name='tipo_relacion',
            field=models.CharField(blank=True, choices=[('cliente', 'Cliente'), ('proveedor', 'Proveedor'), ('ambos', 'Ambos')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cuentacomercial',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cuentas_comerciales', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('activa', 'Activa'), ('cerrada', 'Cerrada'), ('anulada', 'Anulada')], max_length=20),
        ),
        migrations.AlterField(
            model_name='cuentacomercial',
            name='identificacion',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='cuentacomercial',
            name='razon_social',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddIndex(
            model_name='actividadcomercial',
            index=models.Index(fields=['usuario', 'fecha_programada', 'estado'], name='ix_act_com_resp_fecha_estado'),
        ),
        migrations.AddIndex(
            model_name='comunicacion',
            index=models.Index(fields=['solicitud_comercial', 'created_at'], name='ix_com_sol_created_at'),
        ),
        migrations.AddField(
            model_name='cotizaciondetalle',
            name='producto_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_cotizacion', to='productos.productoversion'),
        ),
        migrations.AddField(
            model_name='cotizacionversion',
            name='cotizacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versiones', to='comercial.cotizacion'),
        ),
        migrations.AddField(
            model_name='cotizaciondetalle',
            name='cotizacion_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles', to='comercial.cotizacionversion'),
        ),
        migrations.AddField(
            model_name='especificacionproductosolicitado',
            name='categoria_producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='especificaciones_solicitadas', to='productos.productocategoria'),
        ),
        migrations.AddField(
            model_name='especificacionproductosolicitado',
            name='solicitud_comercial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='especificaciones_producto', to='comercial.solicitudcomercial'),
        ),
        migrations.AddField(
            model_name='especificacionbolsasolicitada',
            name='especificacion_producto_solicitado',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='especificacion_bolsa', to='comercial.especificacionproductosolicitado'),
        ),
        migrations.AddField(
            model_name='especificacionbobinasolicitada',
            name='especificacion_producto_solicitado',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='especificacion_bobina', to='comercial.especificacionproductosolicitado'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='cotizacion_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='comercial.cotizacionversion'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='cuenta_comercial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='comercial.cuentacomercial'),
        ),
        migrations.AddField(
            model_name='pedidodetalle',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles', to='comercial.pedido'),
        ),
        migrations.AddField(
            model_name='pedidodetalle',
            name='producto_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_pedido', to='productos.productoversion'),
        ),
        migrations.RemoveField(
            model_name='comunicacion',
            name='fecha',
        ),
        migrations.AddConstraint(
            model_name='cotizacionversion',
            constraint=models.UniqueConstraint(fields=('cotizacion', 'version'), name='unique_cotizacion_version'),
        ),
    ]
