# Generated by Django 6.1 on 2026-08-27 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0006_cotizaciondetalle_cotizacionversion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='especificacionbolsasolicitada',
            name='acabado_especial',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='especificacionproductosolicitado',
            name='capas',
            field=models.CharField(choices=[('monocapa', 'Monocapa'), ('bicapa', 'Bicapa'), ('tricapa', 'Tricapa')], default='monocapa', max_length=20),
        ),
        migrations.AddField(
            model_name='especificacionproductosolicitado',
            name='cara_impresion',
            field=models.CharField(blank=True, choices=[('anverso', 'Anverso'), ('reverso', 'Reverso'), ('ambas', ' Anverso y Reverso')], max_length=20),
        ),
        migrations.AddField(
            model_name='especificacionproductosolicitado',
            name='tratamiento_impresion',
            field=models.CharField(choices=[('solido', 'Color sólido'), ('degradado', 'Degradado'), ('trameado', 'Trameado')], default='solido', max_length=20),
        ),
    ]
