# Generated by Django 6.1 on 2026-08-27 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0007_especificacionbolsasolicitada_acabado_especial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especificacionproductosolicitado',
            name='cara_impresion',
            field=models.CharField(blank=True, choices=[('anverso', 'Anverso'), ('reverso', 'Reverso'), ('ambas', 'Anverso y Reverso')], max_length=20),
        ),
    ]
