# Generated by Django 6.1 on 2026-08-27 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0008_alter_especificacionproductosolicitado_cara_impresion'),
        ('recursos', '0004_alter_capacidadextrusion_maquinaria'),
    ]

    operations = [
        migrations.AddField(
            model_name='especificacionproductosolicitado',
            name='diseno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='especificaciones_solicitadas', to='recursos.diseno'),
        ),
    ]
