# Generated by Django 6.1 on 2026-08-28 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0009_especificacionproductosolicitado_diseno'),
    ]

    operations = [
        migrations.AddField(
            model_name='especificacionproductosolicitado',
            name='distancia_impresion_abajo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='especificacionproductosolicitado',
            name='distancia_impresion_arriba',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='especificacionproductosolicitado',
            name='distancia_impresion_derecha',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='especificacionproductosolicitado',
            name='distancia_impresion_izquierda',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
