# Generated by Django 6.1 on 2026-09-11 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0010_especificacionproductosolicitado_distancia_impresion_abajo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentacomercial',
            name='numero_documento',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
