# Generated by Django 6.1 on 2026-09-11 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0011_cuentacomercial_numero_documento'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecuenciaCuentaComercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siguiente', models.PositiveIntegerField(default=1)),
            ],
            options={
                'db_table': 'secuencia_cuenta_comercial',
            },
        ),
    ]
