# Generated by Django 6.1 on 2026-09-11 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0012_secuenciacuentacomercial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividadcomercial',
            name='tipo',
            field=models.CharField(choices=[('llamada', 'Llamada'), ('reunion', 'Reunión'), ('cotizacion', 'Cotización'), ('seguimiento', 'Seguimiento'), ('confirmacion', 'Confirmación')], max_length=30),
        ),
    ]
