# Generated by Django 6.1 on 2026-09-14 11:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0013_alter_actividadcomercial_tipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentacomercial',
            name='ejecutivo_asignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cuentas_comerciales_asignadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='solicitudcomercial',
            name='cantidad',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='solicitudcomercial',
            name='fecha_entrega',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitudcomercial',
            name='observaciones',
            field=models.TextField(blank=True),
        ),
    ]
