# Generated by Django 6.1 on 2026-09-14 17:00

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0014_cuentacomercial_ejecutivo_asignado_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitudcomercial',
            old_name='cantidad',
            new_name='cantidad_kg',
        ),
        migrations.AddField(
            model_name='especificacionproductosolicitado',
            name='opacidad',
            field=models.CharField(blank=True, choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], max_length=20),
        ),
        migrations.AddField(
            model_name='especificacionproductosolicitado',
            name='tratamientos_acabados_especiales',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('film_aromatizado', 'Film Aromatizado'), ('oxobiodegradable', 'Oxobiodegradable'), ('perforada', 'Perforada'), ('precorte', 'Precorte')], max_length=30), blank=True, default=list),
        ),
        migrations.AddField(
            model_name='solicitudcomercial',
            name='cantidad_unidades',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='especificacionproductosolicitado',
            name='material',
            field=models.CharField(choices=[('PEAD', 'PEAD'), ('PEBD', 'PEBD'), ('PP', 'PP'), ('BOPP', 'BOPP'), ('OTRO', 'Otro')], max_length=20),
        ),
    ]
