# Generated by Django 6.1 on 2026-09-14 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0015_rename_cantidad_solicitudcomercial_cantidad_kg_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='especificacionbolsasolicitada',
            name='acabado_especial',
        ),
        migrations.AlterField(
            model_name='especificacionbolsasolicitada',
            name='tipo_sello',
            field=models.CharField(choices=[('lateral', 'Lateral'), ('fondo', 'Fondo'), ('ninguno', 'Ninguno')], max_length=100),
        ),
        migrations.AlterField(
            model_name='especificacionbolsasolicitada',
            name='tipo_troquel',
            field=models.CharField(blank=True, choices=[('camiseta', 'Camiseta'), ('normal', 'Normal'), ('rinonera', 'Riñonera'), ('con_asa', 'Con asa'), ('refuerzo', 'Refuerzo'), ('solapa', 'Solapa'), ('adhesiva', 'Adhesiva'), ('cierre_facil', 'Cierre fácil')], max_length=100),
        ),
    ]
