# Generated by Django 6.1 on 2026-09-16 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0016_remove_especificacionbolsasolicitada_acabado_especial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='especificacionproductosolicitado',
            name='distancia_impresion_inferior',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='especificacionproductosolicitado',
            name='distancia_impresion_superior',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='especificacionproductosolicitado',
            name='posicion_impresion',
            field=models.CharField(blank=True, choices=[('centrada', 'Centrada'), ('personalizada', 'Personalizada')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='solicitudcomercial',
            name='lugar_entrega',
            field=models.TextField(blank=True),
        ),
    ]
