# Generated by Django 6.1 on 2026-09-22 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0017_especificacionproductosolicitado_distancia_impresion_inferior_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comunicacion',
            name='direccion',
            field=models.CharField(blank=True, choices=[('saliente', 'Ejecutivo -> Cliente'), ('entrante', 'Cliente -> Ejecutivo')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='comunicacion',
            name='medio',
            field=models.CharField(choices=[('telefono', 'Teléfono'), ('email', 'Correo electrónico'), ('whatsapp', 'WhatsApp'), ('presencial', 'Presencial'), ('videollamada', 'Videollamada'), ('otro', 'Otro')], max_length=30),
        ),
        migrations.AlterField(
            model_name='comunicacion',
            name='tipo',
            field=models.CharField(choices=[('llamada', 'Llamada'), ('correo', 'Correo'), ('mensaje', 'Mensaje'), ('reunion', 'Reunión'), ('visita', 'Visita'), ('otro', 'Otro')], max_length=30),
        ),
    ]
