# Generated by Django 6.1 on 2026-09-22 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0018_comunicacion_direccion_alter_comunicacion_medio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividadcomercial',
            name='solicitud_comercial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='actividades', to='comercial.solicitudcomercial'),
        ),
    ]
