# Generated by Django 6.1 on 2026-09-23 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0019_actividadcomercial_solicitud_comercial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='especificacionproductosolicitado',
            name='distancia_impresion_abajo',
        ),
        migrations.RemoveField(
            model_name='especificacionproductosolicitado',
            name='distancia_impresion_arriba',
        ),
        migrations.AddField(
            model_name='especificacionbobinasolicitada',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='VarianteColorSolicitada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=100)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('especificacion_producto_solicitado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variantes_color', to='comercial.especificacionproductosolicitado')),
            ],
            options={
                'verbose_name': 'Variante de color solicitada',
                'verbose_name_plural': 'Variantes de color solicitadas',
                'db_table': 'variante_color_solicitada',
                'constraints': [models.UniqueConstraint(fields=('especificacion_producto_solicitado', 'color'), name='unique_color_por_especificacion')],
            },
        ),
    ]
