# Generated by Django 6.1 on 2026-09-24 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0020_remove_especificacionproductosolicitado_distancia_impresion_abajo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especificacionbolsasolicitada',
            name='pestana',
            field=models.CharField(choices=[('sin_pestana', 'Sin pestaña'), ('superior', 'Superior'), ('inferior', 'Inferior'), ('ambas', 'Superior e inferior')], default='sin_pestana', max_length=20),
        ),
    ]
