# Generated by Django 6.1 on 2026-09-27 01:04

from django.db import migrations


def crear_secuencia_inicial(apps, schema_editor):
    SecuenciaCuentaComercial = apps.get_model(
        "comercial",
        "SecuenciaCuentaComercial"
    )

    SecuenciaCuentaComercial.objects.get_or_create(
        pk=1,
        defaults={"siguiente": 1},
    )


def eliminar_secuencia_inicial(apps, schema_editor):
    SecuenciaCuentaComercial = apps.get_model(
        "comercial",
        "SecuenciaCuentaComercial"
    )

    SecuenciaCuentaComercial.objects.filter(pk=1).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0021_alter_especificacionbolsasolicitada_pestana'),
    ]

    operations = [
        migrations.RunPython(
            crear_secuencia_inicial,
            eliminar_secuencia_inicial,
        ),
    ]